/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportclassfeespaymentsystem;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hoo Jun Yi
 */
public class CustomerViewSport extends javax.swing.JFrame {

    /**
     * Creates new form CustomerViewSport
     */
    public CustomerViewSport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDayOfTheWeek = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSport = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnFilter = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblWeekDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblSportName = new javax.swing.JLabel();
        cboCoach = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblCharges = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCoachName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCN = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 701));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lblDayOfTheWeek.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblDayOfTheWeek);
        lblDayOfTheWeek.setBounds(184, 538, 103, 16);

        tblSport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Coach Name", "Sport Name", "Sport Charges Per Month", "Day Of The Week", "Time", "Sport Description", "Week Date"
            }
        ));
        tblSport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSportMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSport);
        if (tblSport.getColumnModel().getColumnCount() > 0) {
            tblSport.getColumnModel().getColumn(0).setMinWidth(0);
            tblSport.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(23, 92, 1154, 303);

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel7.setText("Day Of The Week :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 538, 94, 16);

        lblTime.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblTime);
        lblTime.setBounds(184, 561, 103, 16);

        btnFilter.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnFilter.setText("Coach Filter By");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        getContentPane().add(btnFilter);
        btnFilter.setBounds(735, 27, 158, 25);

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel8.setText("Time :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(142, 561, 32, 16);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel3.setText("Coach Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(475, 31, 71, 16);

        lblWeekDate.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblWeekDate);
        lblWeekDate.setBounds(184, 583, 103, 16);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel4.setText("Customer Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(966, 29, 90, 16);

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel9.setText("Week Date :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(112, 583, 62, 16);

        lblSportName.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblSportName);
        lblSportName.setBounds(184, 477, 103, 16);

        getContentPane().add(cboCoach);
        cboCoach.setBounds(549, 28, 168, 20);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel5.setText("Sport Name :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(105, 477, 69, 16);

        lblCharges.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblCharges);
        lblCharges.setBounds(184, 511, 103, 16);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel1.setText("View Sports");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 11, 187, 44);

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel6.setText("Sport Charges Per Month:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(39, 511, 135, 16);

        btnBack.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1081, 511, 96, 57);

        lblCoachName.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblCoachName);
        lblCoachName.setBounds(188, 428, 103, 16);

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel10.setText("Coach Name :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(107, 428, 71, 16);

        lblCN.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblCN);
        lblCN.setBounds(1074, 29, 103, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportclassfeespaymentsystem/Best-Green-Backgrounds.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -30, 1280, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSportMouseClicked
        // TODO add your handling code here:
        int index = tblSport.getSelectedRow();
        TableModel model = tblSport.getModel();
        lblCoachName.setText(model.getValueAt(index,1).toString());
        lblSportName.setText(model.getValueAt(index,2).toString());
        lblCharges.setText(model.getValueAt(index,3).toString());
        lblDayOfTheWeek.setText(model.getValueAt(index,4).toString());
        lblTime.setText(model.getValueAt(index,5).toString());
        lblWeekDate.setText(model.getValueAt(index,7).toString());

    }//GEN-LAST:event_tblSportMouseClicked

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel)tblSport.getModel();
        tableModel.setRowCount(0);
        String line;

        BufferedReader reader;
        try{
            DefaultComboBoxModel option2 = (DefaultComboBoxModel)cboCoach.getModel();
            String c = (String)option2.getElementAt(cboCoach.getSelectedIndex());

            reader = new BufferedReader(new FileReader("Coach.txt"));
            while((line = reader.readLine()) != null)
            {
                if (line.contains(c)) {
                    // Split it.

                    tableModel.addRow(line.split("#"));

                }
            }
            reader.close();
        }

        catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error");
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CustomerMainPage a = new CustomerMainPage();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblCN.setText(Login.name);
        try
{


FileReader input=new FileReader("Login.txt");
BufferedReader output = new BufferedReader(input);
String code;
DefaultComboBoxModel nameopt = new DefaultComboBoxModel();
        cboCoach.setModel(nameopt);
while((code=output.readLine())!=null)
{
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String part1 = parts[1];
String part8 = parts[8];
if (part8.equals("Coach")){
    nameopt.addElement(part1);
}


        
} 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
        
        
                DefaultTableModel tableModel = (DefaultTableModel)tblSport.getModel();
    String line;
    
BufferedReader reader;
    try{       

        reader = new BufferedReader(new FileReader("Coach.txt"));
        while((line = reader.readLine()) != null) 
        {
//            if (line.contains("Customer")) {
    // Split it.
   
    tableModel.addRow(line.split("#")); 

           
//        }
        }
        reader.close();
     }
    
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerViewSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerViewSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerViewSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerViewSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerViewSport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFilter;
    private javax.swing.JComboBox<String> cboCoach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCN;
    private javax.swing.JLabel lblCharges;
    private javax.swing.JLabel lblCoachName;
    private javax.swing.JLabel lblDayOfTheWeek;
    private javax.swing.JLabel lblSportName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWeekDate;
    private javax.swing.JTable tblSport;
    // End of variables declaration//GEN-END:variables
}
