/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportclassfeespaymentsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Hoo Jun Yi
 */
public class CustomerMainPage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerMainPage
     */
    public CustomerMainPage() {
        initComponents();
    }

    CustomerMainPage(String part) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCheckFees = new javax.swing.JButton();
        btnSportCourse = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Main Page");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 323, 44);

        btnCheckFees.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnCheckFees.setText("Check Fees Outstanding");
        btnCheckFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckFeesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckFees);
        btnCheckFees.setBounds(30, 140, 200, 25);

        btnSportCourse.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnSportCourse.setText("View Sports Course");
        btnSportCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSportCourseActionPerformed(evt);
            }
        });
        getContentPane().add(btnSportCourse);
        btnSportCourse.setBounds(30, 260, 200, 25);

        btnLogout.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout);
        btnLogout.setBounds(580, 400, 100, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportclassfeespaymentsystem/Muziek-Beweegt.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 740, 543);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckFeesActionPerformed
        // TODO add your handling code here:
        CheckOutstandingBalance a = new CheckOutstandingBalance();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCheckFeesActionPerformed

    private void btnSportCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSportCourseActionPerformed
        // TODO add your handling code here:
       CustomerViewSport b = new CustomerViewSport();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSportCourseActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int J = JOptionPane.showConfirmDialog(null,"Are you sure you want to log out?","Log Out",JOptionPane.YES_NO_OPTION);
        if(J==0){
            Login e = new Login();
            e.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckFees;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSportCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
