/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportclassfeespaymentsystem;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hoo Jun Yi
 */
public class DeleteCustomerSport extends javax.swing.JFrame {

    /**
     * Creates new form DeleteCustomerSport
     */
    public DeleteCustomerSport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblSport = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblCN = new javax.swing.JLabel();
        lblSportName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCharges = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblExpiredDate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblWeekDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 550));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tblSport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Coach Name", "Customer Name", "Sport Name", "Sport Charges", "Day Of The Week", "Time", "Week Date", "Status", "Expired Date"
            }
        ));
        tblSport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSportMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSport);
        if (tblSport.getColumnModel().getColumnCount() > 0) {
            tblSport.getColumnModel().getColumn(0).setMinWidth(0);
            tblSport.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSport.getColumnModel().getColumn(5).setMinWidth(0);
            tblSport.getColumnModel().getColumn(5).setMaxWidth(0);
            tblSport.getColumnModel().getColumn(6).setMinWidth(0);
            tblSport.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 73, 768, 303);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel4.setText("Delete Customer Sport Record Page");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 20, 710, 40);

        lblCN.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblCN);
        lblCN.setBounds(890, 110, 103, 16);

        lblSportName.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblSportName);
        lblSportName.setBounds(890, 130, 103, 16);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel5.setText("Sport Name :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(810, 130, 69, 16);

        lblCharges.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblCharges);
        lblCharges.setBounds(890, 170, 103, 16);

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel6.setText("Sport Charges :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(800, 170, 80, 16);

        lblStatus.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblStatus);
        lblStatus.setBounds(890, 200, 103, 16);

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel7.setText("Status :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(840, 200, 41, 16);

        lblExpiredDate.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblExpiredDate);
        lblExpiredDate.setBounds(890, 260, 103, 16);

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel8.setText("Expired Date :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(810, 260, 73, 16);

        lblWeekDate.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblWeekDate);
        lblWeekDate.setBounds(890, 230, 103, 16);

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel10.setText("Week Date :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(820, 230, 62, 16);

        btnDelete.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnDelete.setText("Delete Sport Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(810, 320, 160, 25);

        btnBack.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(900, 420, 100, 50);

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel9.setText("Customer Name :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(790, 110, 90, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportclassfeespaymentsystem/Best-Green-Backgrounds.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -16, 1300, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSportMouseClicked
        // TODO add your handling code here:
        int index = tblSport.getSelectedRow();
        TableModel model = tblSport.getModel();
        lblSportName.setText(model.getValueAt(index,3).toString());
        lblCharges.setText(model.getValueAt(index,4).toString());
        lblCN.setText(model.getValueAt(index,2).toString());
        lblStatus.setText(model.getValueAt(index,8).toString());
        lblWeekDate.setText(model.getValueAt(index,7).toString());
        lblExpiredDate.setText(model.getValueAt(index,9).toString());
    }//GEN-LAST:event_tblSportMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel)tblSport.getModel();
    String line;
    
BufferedReader reader;
    try{       

        reader = new BufferedReader(new FileReader("Customer.txt"));
        while((line = reader.readLine()) != null) 
        {
          
   
    tableModel.addRow(line.split("#")); 

           
//        }
        }
        reader.close();
     }
    
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
    }//GEN-LAST:event_formWindowOpened

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        String a = lblCN.getText();
        String b = lblSportName.getText();
        String c = lblCharges.getText();
        String d = lblStatus.getText();
        String e = lblWeekDate.getText();
        String f = lblExpiredDate.getText();
        

        String x;
        if(a.isEmpty()||b.isEmpty()||c.isEmpty()||d.isEmpty()||e.isEmpty()||f.isEmpty()){
            JOptionPane.showMessageDialog(this,"Field Is Empty","Field Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                ArrayList<String> nArray= new ArrayList<>();

                try (FileReader fr = new FileReader("Customer.txt")) {
                    BufferedReader br=new BufferedReader(fr);
                    while(( x= br.readLine()) != null){
                        String[] larray=x.split("#");
                        if(larray[2].equals(a)&&larray[3].equals(b)){
                            

                            x.trim();

                        }
                        else{
                            nArray.add(x);
                        }
                    }   }
                    PrintWriter pw= new PrintWriter("Customer.txt");
                    for(String print:nArray){
                        pw.println(print);
                    }
                    pw.close();
                    JOptionPane.showMessageDialog(this,"Deleted Successfully  ","Deleted", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    new DeleteCustomerSport().setVisible(true);
                }
                catch(Exception m) {
                    m.printStackTrace();
                }

                
                        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        PaymentSelectionPage h = new PaymentSelectionPage();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomerSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomerSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomerSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomerSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteCustomerSport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCN;
    private javax.swing.JLabel lblCharges;
    private javax.swing.JLabel lblExpiredDate;
    private javax.swing.JLabel lblSportName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblWeekDate;
    private javax.swing.JTable tblSport;
    // End of variables declaration//GEN-END:variables
}
