/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportclassfeespaymentsystem;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.*;
import javax.swing.table.*;


/**
 *
 * @author Hoo Jun Yi
 */
public class Delete extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecord = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecord1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel1.setText("Delete Customer & Coach Page");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 11, 482, 44);

        btnBack.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1138, 452, 91, 48);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel2.setText("Username :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(976, 130, 58, 16);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(1052, 127, 112, 20);

        btnDelete.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnDelete.setText("Delete Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(1010, 160, 160, 25);

        tblRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "First Name", "Last Name", "Username", "Password", "Re-Enter Password", "Address", "Contact Number", "Role", "Gender", "Email Address "
            }
        ));
        tblRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecordMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecord);
        if (tblRecord.getColumnModel().getColumnCount() > 0) {
            tblRecord.getColumnModel().getColumn(0).setMinWidth(0);
            tblRecord.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jTabbedPane1.addTab("Customer", jScrollPane1);

        tblRecord1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "First Name", "Last Name", "Username", "Password", "Re-Enter Password", "Address", "Contact Number", "Role", "Gender", "Email Address"
            }
        ));
        tblRecord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecord1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRecord1);
        if (tblRecord1.getColumnModel().getColumnCount() > 0) {
            tblRecord1.getColumnModel().getColumn(0).setMinWidth(0);
            tblRecord1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jTabbedPane1.addTab("Coach", jScrollPane2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 90, 880, 331);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportclassfeespaymentsystem/Best-Green-Backgrounds.jpeg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -40, 1280, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        StaffMainPage a = new StaffMainPage();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel)tblRecord.getModel();
    String line;
    
BufferedReader reader;
    try{       

        reader = new BufferedReader(new FileReader("Login.txt"));
        while((line = reader.readLine()) != null) 
        {
            if (line.contains("Customer")) {
    // Split it.
   
    tableModel.addRow(line.split("#")); 

           
        }
        }
        reader.close();
     }
    
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
     DefaultTableModel tableModel2 = (DefaultTableModel)tblRecord1.getModel();
    String line2;
    
BufferedReader reader2;
    try{       

        reader2 = new BufferedReader(new FileReader("Login.txt"));
        while((line2 = reader2.readLine()) != null) 
        {
            if (line2.contains("Coach")) {
    // Split it.
   
    tableModel2.addRow(line2.split("#")); 

           
        }
        }
        reader2.close();
     }
    
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }

    }//GEN-LAST:event_formWindowOpened
    
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

String g = txtUsername.getText();
String k=new String();
       
       String x;
       if(g.isEmpty()){
           JOptionPane.showMessageDialog(this,"Field Is Empty","Field Error",JOptionPane.ERROR_MESSAGE);
       }
       else{
try { 
         ArrayList<String> nArray= new ArrayList<>();  
         
             try (FileReader fr = new FileReader("login.txt")) {
                 BufferedReader br=new BufferedReader(fr);
                 while(( x= br.readLine()) != null){
                     String[] larray=x.split("#");
                     if(larray[3].equals(g)){
                         k = larray[1];
                         
                         x.trim();
                         
                         
                     }
                     else{
                         nArray.add(x);
                     }
                 }   }
        PrintWriter pw= new PrintWriter("login.txt");
        for(String print:nArray){
            pw.println(print);
        }
        pw.close();
        JOptionPane.showMessageDialog(this,"Deleted Successfully  ","Deleted", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        new Delete().setVisible(true);
        }
        catch(Exception m) {
         m.printStackTrace();
      }

try { 
         ArrayList<String> nArray= new ArrayList<>();  
         
             try (FileReader fr = new FileReader("Coach.txt")) {
                 BufferedReader br=new BufferedReader(fr);
                 while(( x= br.readLine()) != null){
                     String[] larray=x.split("#");
                     if(larray[1].equals(k)){
                         x.trim();
                         
                         
                     }
                     else{
                         nArray.add(x);
                     }
                 }   }
        PrintWriter pw= new PrintWriter("Coach.txt");
        for(String print:nArray){
            pw.println(print);
        }
        pw.close();
        
        
        }
        catch(Exception m) {
         m.printStackTrace();
      }
try { 
         ArrayList<String> nArray= new ArrayList<>();  
         
             try (FileReader fr = new FileReader("Customer.txt")) {
                 BufferedReader br=new BufferedReader(fr);
                 while(( x= br.readLine()) != null){
                     String[] larray=x.split("#");
                     if(larray[1].equals(k)){
                         x.trim();
                         
                         
                     }
                     else{
                         nArray.add(x);
                     }
                 }   }
        PrintWriter pw= new PrintWriter("Customer.txt");
        for(String print:nArray){
            pw.println(print);
        }
        pw.close();
                }
        catch(Exception m) {
         m.printStackTrace();
      }
try { 
         ArrayList<String> nArray= new ArrayList<>();  
         
             try (FileReader fr = new FileReader("Customer.txt")) {
                 BufferedReader br=new BufferedReader(fr);
                 while(( x= br.readLine()) != null){
                     String[] larray=x.split("#");
                     if(larray[2].equals(k)){
                         x.trim();
                         
                         
                     }
                     else{
                         nArray.add(x);
                     }
                 }   }
        PrintWriter pw= new PrintWriter("Customer.txt");
        for(String print:nArray){
            pw.println(print);
        }
        pw.close();
       
       
        }
        catch(Exception m) {
         m.printStackTrace();
      }
       }
       
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void tblRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecordMouseClicked
        // TODO add your handling code here:
        int index = tblRecord.getSelectedRow();
        TableModel model = tblRecord.getModel();
 txtUsername.setText(model.getValueAt(index,3).toString());
    }//GEN-LAST:event_tblRecordMouseClicked

    private void tblRecord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecord1MouseClicked
        // TODO add your handling code here:
        int index = tblRecord1.getSelectedRow();
        TableModel model = tblRecord1.getModel();

        txtUsername.setText(model.getValueAt(index,3).toString());
        
    }//GEN-LAST:event_tblRecord1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblRecord;
    private javax.swing.JTable tblRecord1;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
