/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportclassfeespaymentsystem;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hoo Jun Yi
 */
public class Modify extends javax.swing.JFrame {

    /**
     * Creates new form Modify
     */
    public Modify() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        txtReenter = new javax.swing.JPasswordField();
        txtAddress = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecord = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecord1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1314, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel1.setText("Modify Customer & Coach Page");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 11, 490, 44);

        btnBack.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1131, 438, 100, 50);

        btnModify.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnModify);
        btnModify.setBounds(1000, 440, 100, 50);

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel6.setText("Address :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(968, 321, 48, 16);

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel7.setText("Role :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(980, 184, 30, 16);

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel8.setText("Contact Number :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(923, 359, 93, 16);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel2.setText("First Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(952, 40, 62, 16);

        txtContactNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNumberKeyTyped(evt);
            }
        });
        getContentPane().add(txtContactNumber);
        txtContactNumber.setBounds(1020, 356, 176, 20);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(955, 93, 59, 16);

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel9.setText("Gender :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(966, 211, 44, 16);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel4.setText("Username :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(956, 145, 58, 16);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel5.setText("Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(960, 248, 56, 16);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(1020, 245, 176, 20);

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel11.setText("Re-enter Password :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(912, 274, 104, 16);

        txtReenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReenterActionPerformed(evt);
            }
        });
        getContentPane().add(txtReenter);
        txtReenter.setBounds(1020, 271, 176, 20);
        getContentPane().add(txtAddress);
        txtAddress.setBounds(1020, 318, 176, 20);

        lblFirstName.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblFirstName);
        lblFirstName.setBounds(1024, 40, 176, 16);

        lblLastName.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblLastName);
        lblLastName.setBounds(1024, 93, 176, 16);

        lblUsername.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblUsername);
        lblUsername.setBounds(1024, 145, 176, 16);

        lblGender.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblGender);
        lblGender.setBounds(1020, 211, 180, 16);

        lblRole.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblRole);
        lblRole.setBounds(1020, 184, 180, 16);

        tblRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "First Name", "Last Name", "Username", "Password", "Re-Enter Password", "Address", "Contact Number", "Role", "Gender", "Email Address "
            }
        ));
        tblRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecordMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecord);
        if (tblRecord.getColumnModel().getColumnCount() > 0) {
            tblRecord.getColumnModel().getColumn(0).setMinWidth(0);
            tblRecord.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jTabbedPane1.addTab("Customer", jScrollPane1);

        tblRecord1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "First Name", "Last Name", "Username", "Password", "Re-Enter Password", "Address", "Contact Number", "Role", "Gender", "Email Address"
            }
        ));
        tblRecord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecord1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRecord1);
        if (tblRecord1.getColumnModel().getColumnCount() > 0) {
            tblRecord1.getColumnModel().getColumn(0).setMinWidth(0);
            tblRecord1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jTabbedPane1.addTab("Coach", jScrollPane2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(32, 85, 870, 331);

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel10.setText("Email Address :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(937, 397, 79, 16);
        getContentPane().add(txtEmailAddress);
        txtEmailAddress.setBounds(1020, 394, 176, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportclassfeespaymentsystem/Best-Green-Backgrounds.jpeg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, -6, 1340, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        StaffMainPage a = new StaffMainPage();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel)tblRecord.getModel();
    String line;
    
BufferedReader reader;
    try{       

        reader = new BufferedReader(new FileReader("Login.txt"));
        while((line = reader.readLine()) != null) 
        {
            if (line.contains("Customer")) {
    // Split it.
   
    tableModel.addRow(line.split("#")); 

           
        }
        }
        reader.close();
     }
    
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
     DefaultTableModel tableModel2 = (DefaultTableModel)tblRecord1.getModel();
    String line2;
    
BufferedReader reader2;
    try{       

        reader2 = new BufferedReader(new FileReader("Login.txt"));
        while((line2 = reader2.readLine()) != null) 
        {
            if (line2.contains("Coach")) {
    // Split it.
   
    tableModel2.addRow(line2.split("#")); 

           
        }
        }
        reader2.close();
     }
    
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
    }//GEN-LAST:event_formWindowOpened

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
         String a = new String(txtPassword.getPassword());
        String b = new String(txtReenter.getPassword());
       
       String c = lblRole.getText();
       String d = lblGender.getText();
       String e = lblFirstName.getText();
       String f = lblLastName.getText();
       String g = lblUsername.getText();
       String h = txtAddress.getText();
       String i = txtContactNumber.getText();
       String l = txtEmailAddress.getText();
       String x;
       if(e.isEmpty()||f.isEmpty()||g.isEmpty()||h.isEmpty()||i.isEmpty()||a.isEmpty()||b.isEmpty()){
           JOptionPane.showMessageDialog(this,"No Field Is Enter Or One Field Is Empty","Field Error",JOptionPane.ERROR_MESSAGE);
       }
       else{
           if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", txtEmailAddress.getText()))) { 
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE); 
        } 
        else 
        {
            if(txtReenter.getText().equals(txtPassword.getText())){
             
try { 
         ArrayList<String> nArray= new ArrayList<>();  
         
             try (FileReader fr = new FileReader("login.txt")) {
                 BufferedReader br=new BufferedReader(fr);
                 while(( x= br.readLine()) != null){
                     String[] larray=x.split("#");
                     if(larray[3].equals(g)){
                         nArray.add("#"+e+"#"+f+"#"+g+"#"+a+"#"+b+"#"+h+"#"+i+"#"+c+"#"+d+"#"+l);
                         
                         
                     }
                     else{
                         nArray.add(x);
                     }
                 }   }
        PrintWriter pw= new PrintWriter("login.txt");
        for(String print:nArray){
            pw.println(print);
        }
        pw.close();
        JOptionPane.showMessageDialog(this,"Modify Successfully  ","Modify", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        new Modify().setVisible(true);
        }
        catch(Exception m) {
         m.printStackTrace();
      }
            }
            else{
               JOptionPane.showMessageDialog(null, "Password is not match", "Error", JOptionPane.ERROR_MESSAGE);
            }
       }
       }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void txtContactNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNumberKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtContactNumberKeyTyped

    private void txtReenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReenterActionPerformed

    private void tblRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecordMouseClicked
        // TODO add your handling code here:
        int index = tblRecord.getSelectedRow();
        TableModel model = tblRecord.getModel();

        lblUsername.setText(model.getValueAt(index,3).toString());
        lblFirstName.setText(model.getValueAt(index,1).toString());
        lblLastName.setText(model.getValueAt(index,2).toString());
        txtPassword.setText(model.getValueAt(index,4).toString());
        txtReenter.setText(model.getValueAt(index,5).toString());
        txtAddress.setText(model.getValueAt(index,6).toString());
        lblRole.setText(model.getValueAt(index,8).toString());
        txtEmailAddress.setText(model.getValueAt(index,10).toString());
        lblGender.setText(model.getValueAt(index,9).toString());
        txtContactNumber.setText(model.getValueAt(index,7).toString());
    }//GEN-LAST:event_tblRecordMouseClicked

    private void tblRecord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecord1MouseClicked
        // TODO add your handling code here:
        int index = tblRecord1.getSelectedRow();
        TableModel model = tblRecord1.getModel();

               lblUsername.setText(model.getValueAt(index,3).toString());
        lblFirstName.setText(model.getValueAt(index,1).toString());
        lblLastName.setText(model.getValueAt(index,2).toString());
        txtPassword.setText(model.getValueAt(index,4).toString());
        txtReenter.setText(model.getValueAt(index,5).toString());
        txtAddress.setText(model.getValueAt(index,6).toString());
        lblRole.setText(model.getValueAt(index,8).toString());
        txtEmailAddress.setText(model.getValueAt(index,10).toString());
        lblGender.setText(model.getValueAt(index,9).toString());
        txtContactNumber.setText(model.getValueAt(index,7).toString());
    }//GEN-LAST:event_tblRecord1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblRecord;
    private javax.swing.JTable tblRecord1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtReenter;
    // End of variables declaration//GEN-END:variables
}
