/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportclassfeespaymentsystem;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.temporal.TemporalField;
import java.time.temporal.WeekFields;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hoo Jun Yi
 */
public class ModifySport extends javax.swing.JFrame {

    /**
     * Creates new form ModifySport
     */
    public ModifySport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn6 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btn9 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btn11 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btn12 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn7 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn19 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        lblCoachName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSportName = new javax.swing.JTextField();
        txtCharges = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboDOTW = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cboTime = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblWeekDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnBack2 = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 550));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btn6.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(592, 86, 86, 58);

        btn8.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8);
        btn8.setBounds(197, 158, 89, 48);

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel7.setText("Tuesday");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(51, 171, 44, 16);

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel8.setText("Wednesday");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(34, 247, 61, 16);

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel9.setText("Thursday");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(46, 301, 49, 16);

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel10.setText("Friday");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(63, 383, 32, 16);

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel11.setText("10-12");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(109, 67, 28, 16);

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel12.setText("13-15");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(222, 67, 28, 16);

        jLabel13.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel13.setText("15-17");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(309, 67, 28, 16);

        btn10.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10);
        btn10.setBounds(388, 150, 88, 54);

        jLabel14.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel14.setText("17-19");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(405, 67, 29, 16);

        btn9.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9);
        btn9.setBounds(292, 153, 90, 48);

        jLabel15.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel15.setText("20-22");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(496, 67, 28, 16);

        btn11.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn11);
        btn11.setBounds(482, 150, 80, 54);

        jLabel16.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel16.setText("22-23");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(608, 67, 28, 16);

        btn12.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        getContentPane().add(btn12);
        btn12.setBounds(592, 155, 86, 56);

        btn14.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        getContentPane().add(btn14);
        btn14.setBounds(197, 217, 89, 53);

        btn16.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });
        getContentPane().add(btn16);
        btn16.setBounds(388, 222, 88, 55);

        btn15.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        getContentPane().add(btn15);
        btn15.setBounds(292, 222, 90, 53);

        btn17.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });
        getContentPane().add(btn17);
        btn17.setBounds(482, 222, 80, 55);

        btn18.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });
        getContentPane().add(btn18);
        btn18.setBounds(592, 229, 86, 55);

        btn20.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        getContentPane().add(btn20);
        btn20.setBounds(197, 288, 89, 48);

        jLabel17.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel17.setText("Day/Time");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(28, 67, 50, 16);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel1.setText("Modify or Delete Sport Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 12, 470, 44);

        btn7.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(99, 158, 88, 48);

        btn22.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        getContentPane().add(btn22);
        btn22.setBounds(388, 288, 88, 48);

        btn21.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        getContentPane().add(btn21);
        btn21.setBounds(292, 288, 90, 48);

        btn23.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });
        getContentPane().add(btn23);
        btn23.setBounds(482, 288, 80, 48);

        btn24.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });
        getContentPane().add(btn24);
        btn24.setBounds(592, 295, 86, 48);

        btn29.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn29ActionPerformed(evt);
            }
        });
        getContentPane().add(btn29);
        btn29.setBounds(482, 361, 80, 48);

        btn30.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });
        getContentPane().add(btn30);
        btn30.setBounds(592, 361, 86, 48);

        btn26.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn26ActionPerformed(evt);
            }
        });
        getContentPane().add(btn26);
        btn26.setBounds(197, 361, 89, 48);

        btn1.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(99, 89, 88, 58);

        btn28.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn28ActionPerformed(evt);
            }
        });
        getContentPane().add(btn28);
        btn28.setBounds(388, 361, 88, 48);

        btn25.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25ActionPerformed(evt);
            }
        });
        getContentPane().add(btn25);
        btn25.setBounds(99, 361, 88, 48);

        btn27.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn27ActionPerformed(evt);
            }
        });
        getContentPane().add(btn27);
        btn27.setBounds(292, 361, 90, 48);

        btn13.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        getContentPane().add(btn13);
        btn13.setBounds(99, 224, 88, 53);

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel6.setText("Monday");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(52, 113, 43, 16);

        btn19.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn19ActionPerformed(evt);
            }
        });
        getContentPane().add(btn19);
        btn19.setBounds(99, 288, 88, 48);

        btn2.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(197, 89, 89, 58);

        btn4.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(388, 89, 84, 55);

        btn3.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(292, 89, 90, 58);

        btn5.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(482, 89, 80, 55);

        lblCoachName.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblCoachName);
        lblCoachName.setBounds(1038, 86, 112, 23);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel2.setText("Coach Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(949, 86, 71, 16);
        getContentPane().add(txtSportName);
        txtSportName.setBounds(1047, 120, 128, 20);

        txtCharges.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChargesKeyTyped(evt);
            }
        });
        getContentPane().add(txtCharges);
        txtCharges.setBounds(1047, 158, 128, 20);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel3.setText("Sport Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(960, 123, 69, 16);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel5.setText("Sport Charges :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(949, 161, 80, 16);

        cboDOTW.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        getContentPane().add(cboDOTW);
        cboDOTW.setBounds(1044, 196, 117, 20);

        jLabel18.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel18.setText("Day Of The Week :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(932, 199, 94, 16);

        cboTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10-12", "13-15", "15-17", "17-19", "20-22", "22-23" }));
        getContentPane().add(cboTime);
        cboTime.setBounds(1044, 227, 117, 20);

        jLabel19.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel19.setText("Time :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(994, 230, 32, 16);

        jLabel20.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel20.setText("Week Date :");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(961, 279, 62, 16);

        lblWeekDate.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblWeekDate);
        lblWeekDate.setBounds(1041, 279, 112, 23);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel4.setText("Sport Description :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(932, 313, 98, 16);

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1048, 313, 166, 96);

        btnBack2.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack2);
        btnBack2.setBounds(1148, 431, 70, 50);

        btnModify.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnModify);
        btnModify.setBounds(953, 431, 90, 50);

        btnDelete.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(1058, 431, 80, 50);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportclassfeespaymentsystem/Best-Green-Backgrounds.jpeg"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(3, -6, 1310, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(0);
        cboTime.setSelectedIndex(5);
         try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Monday") && part5.equals("22-23")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(1);
        cboTime.setSelectedIndex(1);
                try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Tuesday") && part5.equals("13-15")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(1);
        cboTime.setSelectedIndex(3);
                try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Tuesday") && part5.equals("17-19")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(1);
        cboTime.setSelectedIndex(2);
                try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Tuesday") && part5.equals("15-17")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(1);
        cboTime.setSelectedIndex(4);
                try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Tuesday") && part5.equals("20-22")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(1);
        cboTime.setSelectedIndex(5);
                try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Tuesday") && part5.equals("22-23")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(2);
        cboTime.setSelectedIndex(1);
                     try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Wednesday") && part5.equals("13-15")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(2);
        cboTime.setSelectedIndex(3);
                     try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Wednesday") && part5.equals("17-19")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn16ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(2);
        cboTime.setSelectedIndex(2);
                     try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Wednesday") && part5.equals("15-17")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(2);
        cboTime.setSelectedIndex(4);
                     try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Wednesday") && part5.equals("20-22")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn17ActionPerformed

    private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(2);
        cboTime.setSelectedIndex(5);
                     try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Wednesday") && part5.equals("22-23")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn18ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(3);
        cboTime.setSelectedIndex(1);
        try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Thursday") && part5.equals("13-15")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(1);
        cboTime.setSelectedIndex(0);
         try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Tuesday") && part5.equals("10-12")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(3);
        cboTime.setSelectedIndex(3);
        try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Thursday") && part5.equals("17-19")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(3);
        cboTime.setSelectedIndex(2);
        try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Thursday") && part5.equals("15-17")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(3);
        cboTime.setSelectedIndex(4);
        try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Thursday") && part5.equals("20-22")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(3);
        cboTime.setSelectedIndex(5);
        try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Thursday") && part5.equals("22-23")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn24ActionPerformed

    private void btn29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn29ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(4);
        cboTime.setSelectedIndex(4);
          try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Friday") && part5.equals("20-22")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn29ActionPerformed

    private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(4);
        cboTime.setSelectedIndex(5);
          try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Friday") && part5.equals("22-23")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn30ActionPerformed

    private void btn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn26ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(4);
        cboTime.setSelectedIndex(1);
          try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Friday") && part5.equals("13-15")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn26ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(0);
        cboTime.setSelectedIndex(0);
         
        try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Monday") && part5.equals("10-12")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn28ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(4);
        cboTime.setSelectedIndex(3);
          try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Friday") && part5.equals("17-19")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn28ActionPerformed

    private void btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(4);
        cboTime.setSelectedIndex(0);
        try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Friday") && part5.equals("10-12")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn25ActionPerformed

    private void btn27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn27ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(4);
        cboTime.setSelectedIndex(2);
          try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Friday") && part5.equals("15-17")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn27ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(2);
        cboTime.setSelectedIndex(0);
                try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Wednesday") && part5.equals("10-12")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn19ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(3);
        cboTime.setSelectedIndex(0);
                     try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Thursday") && part5.equals("10-12")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn19ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(0);
        cboTime.setSelectedIndex(1);
         try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Monday") && part5.equals("13-15")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(0);
        cboTime.setSelectedIndex(3);
         try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Monday") && part5.equals("17-19")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(0);
        cboTime.setSelectedIndex(2);
         try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Monday") && part5.equals("15-17")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        cboDOTW.setSelectedIndex(0);
        cboTime.setSelectedIndex(4);
         try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
        String wk = lblWeekDate.getText();
       
    
    if (part4.equals("Monday") && part5.equals("20-22")&& part7.equals(wk) && part1.equals(name))
{
     txtSportName.setText(part2);
     txtCharges.setText(part3);
     txtDescription.setText(part6);
     
    
    
}
    } 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_btn5ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        CouchMainPage a = new CouchMainPage();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:

        if(lblCoachName.getText().isEmpty()==true ||txtSportName.getText().isEmpty()==true || txtCharges.getText().isEmpty()==true || txtDescription.getText().isEmpty()==true||lblWeekDate.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(this,"No Field Is Enter Or One Field Is Empty","Field Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
String a = lblCoachName.getText();
String b = txtSportName.getText();
String c = txtCharges.getText();
DefaultComboBoxModel option = (DefaultComboBoxModel)cboDOTW.getModel();
       String d = (String)option.getElementAt(cboDOTW.getSelectedIndex());
        DefaultComboBoxModel option2 = (DefaultComboBoxModel)cboTime.getModel();
       String e = (String)option2.getElementAt(cboTime.getSelectedIndex());
       String wk = lblWeekDate.getText();
       String f = txtDescription.getText();
                 String x;
try { 
         ArrayList<String> nArray= new ArrayList<>();  
         
             try (FileReader fr = new FileReader("Coach.txt")) {
                 BufferedReader br=new BufferedReader(fr);
                 while(( x= br.readLine()) != null){
                     String[] larray=x.split("#");
                     if(larray[1].equals(a)&&larray[2].equals(b)&&larray[7].equals(wk)){
                         nArray.add("#"+a+"#"+b+"#"+c+"#"+d+"#"+e+"#"+f+"#"+wk);
                         
                         
                     }
                     else{
                         nArray.add(x);
                     }
                 }   }
        PrintWriter pw= new PrintWriter("Coach.txt");
        for(String print:nArray){
            pw.println(print);
        }
        pw.close();
        JOptionPane.showMessageDialog(this,"Modify Successfully  ","Modify", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        new ModifySport().setVisible(true);
        }
        catch(Exception m) {
         m.printStackTrace();
      }
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         btn1.setBackground(Color.green);
        btn2.setBackground(Color.green);
        btn3.setBackground(Color.green);
        btn4.setBackground(Color.green);
        btn5.setBackground(Color.green);
        btn6.setBackground(Color.green);
        btn7.setBackground(Color.green);
        btn8.setBackground(Color.green);
        btn9.setBackground(Color.green);
        btn10.setBackground(Color.green);
                btn11.setBackground(Color.green);
        btn12.setBackground(Color.green);
        btn13.setBackground(Color.green);
        btn14.setBackground(Color.green);
        btn15.setBackground(Color.green);
        btn16.setBackground(Color.green);
        btn17.setBackground(Color.green);
        btn18.setBackground(Color.green);
        btn19.setBackground(Color.green);
        btn20.setBackground(Color.green);
                btn21.setBackground(Color.green);
        btn22.setBackground(Color.green);
        btn23.setBackground(Color.green);
        btn24.setBackground(Color.green);
        btn25.setBackground(Color.green);
        btn26.setBackground(Color.green);
        btn27.setBackground(Color.green);
        btn28.setBackground(Color.green);
        btn29.setBackground(Color.green);
        btn30.setBackground(Color.green);
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        btn12.setEnabled(false);
        btn13.setEnabled(false);
        btn14.setEnabled(false);
        btn15.setEnabled(false);
        btn16.setEnabled(false);
        btn17.setEnabled(false);
        btn18.setEnabled(false);
        btn19.setEnabled(false);
        btn20.setEnabled(false);
        btn21.setEnabled(false);
        btn22.setEnabled(false);
        btn23.setEnabled(false);
        btn24.setEnabled(false);
        btn25.setEnabled(false);
        btn26.setEnabled(false);
        btn27.setEnabled(false);
        btn28.setEnabled(false);
        btn29.setEnabled(false);
        btn30.setEnabled(false);
        LocalDate date = LocalDate.now();
TemporalField fieldISO = WeekFields.of(Locale.FRANCE).dayOfWeek();
lblWeekDate.setText(date.with(fieldISO, 1).toString()); 
        lblCoachName.setText(Login.name);
        
        try
{


FileReader input=new FileReader("Coach.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");

String a = txtSportName.getText();
String b = txtCharges.getText();
String c = txtDescription.getText();
String wk = lblWeekDate.getText();
String name = lblCoachName.getText();
String part1 = parts[1];
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];


if (part4.equals("Monday") && part5.equals("10-12")&& part7.equals(wk) && part1.equals(name))
{
    btn1.setEnabled(true);
    btn1.setBackground(Color.blue);
    btn1.setText(part2);
    
    
}
if (part4.equals("Monday") && part5.equals("13-15")&& part7.equals(wk)&& part1.equals(name))
{
    btn2.setEnabled(true);
    btn2.setBackground(Color.blue);
    btn2.setText(part2);
}
if (part4.equals("Monday") && part5.equals("15-17")&& part7.equals(wk)&& part1.equals(name))
{
    btn3.setEnabled(true);
    btn3.setBackground(Color.blue);
    btn3.setText(part2);
}
if (part4.equals("Monday") && part5.equals("17-19")&& part7.equals(wk)&& part1.equals(name))
{
    btn4.setEnabled(true);
    btn4.setBackground(Color.blue);
    btn4.setText(part2);
}
if (part4.equals("Monday") && part5.equals("20-22")&& part7.equals(wk)&& part1.equals(name))
{
    btn5.setEnabled(true);
    btn5.setBackground(Color.blue);
    btn5.setText(part2);
}
if (part4.equals("Monday") && part5.equals("22-23")&& part7.equals(wk)&& part1.equals(name))
{
    btn6.setEnabled(true);
    btn6.setBackground(Color.blue);
    btn6.setText(part2);
}
if (part4.equals("Tuesday") && part5.equals("10-12")&& part7.equals(wk)&& part1.equals(name))
{
    btn7.setEnabled(true);
    btn7.setBackground(Color.blue);
    btn7.setText(part2);
}
if (part4.equals("Tuesday") && part5.equals("13-15")&& part7.equals(wk)&& part1.equals(name))
{
    btn8.setEnabled(true);
    btn8.setBackground(Color.blue);
    btn8.setText(part2);
}
if (part4.equals("Tuesday") && part5.equals("15-17")&& part7.equals(wk)&& part1.equals(name))
{
    btn9.setEnabled(true);
    btn9.setBackground(Color.blue);
    btn9.setText(part2);
}
if (part4.equals("Tuesday") && part5.equals("17-19")&& part7.equals(wk)&& part1.equals(name))
{
    btn10.setEnabled(true);
    btn10.setBackground(Color.blue);
    btn10.setText(part2);
}
if (part4.equals("Tuesday") && part5.equals("20-22")&& part7.equals(wk)&& part1.equals(name))
{
    btn11.setEnabled(true);
    btn11.setBackground(Color.blue);
    btn11.setText(part2);
}
if (part4.equals("Tuesday") && part5.equals("22-23")&& part7.equals(wk)&& part1.equals(name))
{
    btn12.setEnabled(true);
    btn12.setBackground(Color.blue);
    btn12.setText(part2);
}
if (part4.equals("Wednesday") && part5.equals("10-12")&& part7.equals(wk)&& part1.equals(name))
{
    btn13.setEnabled(true);
    btn13.setBackground(Color.blue);
    btn13.setText(part2);
}
if (part4.equals("Wednesday") && part5.equals("13-15")&& part7.equals(wk)&& part1.equals(name))
{
    btn14.setEnabled(true);
    btn14.setBackground(Color.blue);
    btn14.setText(part2);
}
if (part4.equals("Wednesday") && part5.equals("15-17")&& part7.equals(wk)&& part1.equals(name))
{
    btn15.setEnabled(true);
    btn15.setBackground(Color.blue);
    btn15.setText(part2);
}
if (part4.equals("Wednesday") && part5.equals("17-19")&& part7.equals(wk)&& part1.equals(name))
{
    btn16.setEnabled(true);
    btn16.setBackground(Color.blue);
    btn16.setText(part2);
}
if (part4.equals("Wednesday") && part5.equals("20-22")&& part7.equals(wk)&& part1.equals(name))
{
    btn17.setEnabled(true);
    btn17.setBackground(Color.blue);
    btn17.setText(part2);
}
if (part4.equals("Wednesday") && part5.equals("22-23")&& part7.equals(wk)&& part1.equals(name))
{
    btn18.setEnabled(true);
    btn18.setBackground(Color.blue);
    btn18.setText(part2);
}
if (part4.equals("Thursday") && part5.equals("10-12")&& part7.equals(wk)&& part1.equals(name))
{
    btn19.setEnabled(true);
    btn19.setBackground(Color.blue);
    btn19.setText(part2);
}
if (part4.equals("Thursday") && part5.equals("13-15")&& part7.equals(wk)&& part1.equals(name))
{
    btn20.setEnabled(true);
    btn20.setBackground(Color.blue);
    btn20.setText(part2);
}
if (part4.equals("Thursday") && part5.equals("15-17")&& part7.equals(wk)&& part1.equals(name))
{
    btn21.setEnabled(true);
    btn21.setBackground(Color.blue);
    btn21.setText(part2);
}
if (part4.equals("Thursday") && part5.equals("17-19")&& part7.equals(wk)&& part1.equals(name))
{
    btn22.setEnabled(true);
    btn22.setBackground(Color.blue);
    btn22.setText(part2);
}
if (part4.equals("Thursday") && part5.equals("20-22")&& part7.equals(wk)&& part1.equals(name))
{
    btn23.setEnabled(true);
    btn23.setBackground(Color.blue);
    btn23.setText(part2);
}
if (part4.equals("Thursday") && part5.equals("22-23")&& part7.equals(wk)&& part1.equals(name))
{
    btn24.setEnabled(true);
    btn24.setBackground(Color.blue);
    btn24.setText(part2);
}
if (part4.equals("Friday") && part5.equals("10-12")&& part7.equals(wk)&& part1.equals(name))
{
    btn25.setEnabled(true);
    btn25.setBackground(Color.blue);
    btn25.setText(part2);
}
if (part4.equals("Friday") && part5.equals("13-15")&& part7.equals(wk)&& part1.equals(name))
{
    btn26.setEnabled(true);
    btn26.setBackground(Color.blue);
    btn26.setText(part2);
}
if (part4.equals("Friday") && part5.equals("15-17")&& part7.equals(wk)&& part1.equals(name))
{
    btn27.setEnabled(true);
    btn27.setBackground(Color.blue);
    btn27.setText(part2);
}
if (part4.equals("Friday") && part5.equals("17-19")&& part7.equals(wk)&& part1.equals(name))
{
    btn28.setEnabled(true);
    btn28.setBackground(Color.blue);
    btn28.setText(part2);
}
if (part4.equals("Friday") && part5.equals("20-22")&& part7.equals(wk)&& part1.equals(name))
{
    btn29.setEnabled(true);
    btn29.setBackground(Color.blue);
    btn29.setText(part2);
}
if (part4.equals("Friday") && part5.equals("22-23")&& part7.equals(wk)&& part1.equals(name))
{
    btn30.setEnabled(true);
    btn30.setBackground(Color.blue);
    btn30.setText(part2);
}
} 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
    }//GEN-LAST:event_formWindowOpened

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(txtSportName.getText().isEmpty()==true || txtCharges.getText().isEmpty()==true || txtDescription.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(this,"No Field Is Enter Or One Field Is Empty","Field Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
String a = lblCoachName.getText();
String b = txtSportName.getText();
String c = txtCharges.getText();
DefaultComboBoxModel option = (DefaultComboBoxModel)cboDOTW.getModel();
       String d = (String)option.getElementAt(cboDOTW.getSelectedIndex());
        DefaultComboBoxModel option2 = (DefaultComboBoxModel)cboTime.getModel();
       String e = (String)option2.getElementAt(cboTime.getSelectedIndex());
       String wk = lblWeekDate.getText();
       String f = txtDescription.getText();
                 String x;
try { 
         ArrayList<String> nArray= new ArrayList<>();  
         
             try (FileReader fr = new FileReader("Coach.txt")) {
                 BufferedReader br=new BufferedReader(fr);
                 while(( x= br.readLine()) != null){
                     String[] larray=x.split("#");
                     if(larray[1].equals(a)&&larray[2].equals(b)&&larray[7].equals(wk)){
                         x.trim();
                         
                         
                     }
                     else{
                         nArray.add(x);
                     }
                 }   }
        PrintWriter pw= new PrintWriter("Coach.txt");
        for(String print:nArray){
            pw.println(print);
        }
        pw.close();
        JOptionPane.showMessageDialog(this,"Delete Successfully  ","Delete", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        new ModifySport().setVisible(true);
        }
        catch(Exception m) {
         m.printStackTrace();
      }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtChargesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChargesKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
           getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtChargesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifySport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifySport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifySport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifySport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifySport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JComboBox<String> cboDOTW;
    private javax.swing.JComboBox<String> cboTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCoachName;
    private javax.swing.JLabel lblWeekDate;
    private javax.swing.JTextField txtCharges;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtSportName;
    // End of variables declaration//GEN-END:variables
}
