/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportclassfeespaymentsystem;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.temporal.TemporalField;
import java.time.temporal.WeekFields;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hoo Jun Yi
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }
   public void ViewAllSport(String d,String f,String g,String j){
       lblCN.setText(d);
       lblSportName.setText(f);
       lblCharges.setText(g);
       lblWeekDate.setText(j);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSport = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblCN = new javax.swing.JLabel();
        lblSportName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCharges = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblExpiredDate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboDuration = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lblWeekDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNewExpiredDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSelectDuration = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblAmountPay = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnProceedPayment = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 596));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel1.setText("Payment Page / Extend Duration Page");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(45, 11, 630, 44);

        tblSport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Coach Name", "Customer Name", "Sport Name", "Sport Charges", "Day Of The Week", "Time", "Week Date", "Status", "Expired Date"
            }
        ));
        tblSport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSportMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSport);
        if (tblSport.getColumnModel().getColumnCount() > 0) {
            tblSport.getColumnModel().getColumn(0).setMinWidth(0);
            tblSport.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSport.getColumnModel().getColumn(5).setMinWidth(0);
            tblSport.getColumnModel().getColumn(5).setMaxWidth(0);
            tblSport.getColumnModel().getColumn(6).setMinWidth(0);
            tblSport.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 73, 768, 303);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel4.setText("Customer Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(790, 110, 90, 16);

        lblCN.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblCN);
        lblCN.setBounds(890, 110, 103, 16);

        lblSportName.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblSportName);
        lblSportName.setBounds(890, 130, 103, 16);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel5.setText("Sport Name :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(810, 130, 69, 16);

        lblCharges.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblCharges);
        lblCharges.setBounds(890, 170, 103, 16);

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel6.setText("Sport Charges :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(800, 170, 80, 16);

        lblStatus.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblStatus);
        lblStatus.setBounds(890, 200, 103, 16);

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel7.setText("Status :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(840, 200, 41, 16);

        lblExpiredDate.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblExpiredDate);
        lblExpiredDate.setBounds(890, 260, 103, 16);

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel8.setText("Expired Date :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(810, 260, 73, 16);

        cboDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One Month", "Three Month", "Nine Month", "One Year", " " }));
        cboDuration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDurationKeyPressed(evt);
            }
        });
        getContentPane().add(cboDuration);
        cboDuration.setBounds(234, 412, 142, 20);

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel9.setText("Duration :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(171, 415, 53, 16);

        lblWeekDate.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblWeekDate);
        lblWeekDate.setBounds(890, 230, 103, 16);

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel10.setText("Week Date :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(820, 230, 62, 16);

        lblNewExpiredDate.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblNewExpiredDate);
        lblNewExpiredDate.setBounds(277, 464, 103, 16);

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel11.setText("New Expired Date :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(168, 464, 99, 16);

        btnSelectDuration.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnSelectDuration.setText("Select Duration");
        btnSelectDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectDurationActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectDuration);
        btnSelectDuration.setBounds(411, 411, 163, 25);

        btnBack.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(920, 470, 83, 56);

        lblAmountPay.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblAmountPay);
        lblAmountPay.setBounds(293, 514, 103, 16);

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel12.setText("Amount Have To Pay :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(168, 514, 115, 16);

        btnProceedPayment.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnProceedPayment.setText("Proceed Payment");
        btnProceedPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btnProceedPayment);
        btnProceedPayment.setBounds(424, 508, 162, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportclassfeespaymentsystem/Best-Green-Backgrounds.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -50, 1290, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSportMouseClicked
        // TODO add your handling code here:
        int index = tblSport.getSelectedRow();
        TableModel model = tblSport.getModel();
        lblSportName.setText(model.getValueAt(index,3).toString());
        lblCharges.setText(model.getValueAt(index,4).toString());
        lblCN.setText(model.getValueAt(index,2).toString());
        lblStatus.setText(model.getValueAt(index,8).toString());
        lblWeekDate.setText(model.getValueAt(index,7).toString());
        lblExpiredDate.setText(model.getValueAt(index,9).toString());
    }//GEN-LAST:event_tblSportMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
           try
{


FileReader input=new FileReader("Customer.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String part1 = parts[1]; 
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
String part8 = parts[8];
String part9 = parts[9];

if (lblCN.getText().equals(part2)&&lblSportName.getText().equals(part3) && lblCharges.getText().equals(part4)&& lblWeekDate.getText().equals(part7))
{
    lblStatus.setText(part8);
    lblExpiredDate.setText(part9);
}
} 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
                
DefaultTableModel tableModel = (DefaultTableModel)tblSport.getModel();
    String line;
    
BufferedReader reader;
    try{       

        reader = new BufferedReader(new FileReader("Customer.txt"));
        while((line = reader.readLine()) != null) 
        {
          
   
    tableModel.addRow(line.split("#")); 

           
//        }
        }
        reader.close();
     }
    
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
    }//GEN-LAST:event_formWindowOpened

    private void cboDurationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDurationKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboDurationKeyPressed

    private void btnSelectDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectDurationActionPerformed
        // TODO add your handling code here:
        if(lblCN.getText().isEmpty() || lblSportName.getText().isEmpty() || lblCharges.getText().isEmpty()||lblStatus.getText().isEmpty()|| lblWeekDate.getText().isEmpty() || lblExpiredDate.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"No Field Is Given Or One Field Is Empty! Please Select Data From Table!","Field Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            DefaultComboBoxModel option = (DefaultComboBoxModel)cboDuration.getModel();
       String c = (String)option.getElementAt(cboDuration.getSelectedIndex());
      String da = lblWeekDate.getText();
       if (c.equals("One Month"))
       {
           
           LocalDate date1 = LocalDate.parse(da);
                LocalDate date2 = date1.plusMonths(1);
TemporalField fieldISO = WeekFields.of(Locale.FRANCE).dayOfWeek();
lblNewExpiredDate.setText(date2.with(fieldISO, 1).toString()); 
 int k = Integer.parseInt(lblCharges.getText())*1;
 lblAmountPay.setText(Integer.toString(k));
       }
       else if (c.equals("Three Month")){
        
           LocalDate date1 = LocalDate.parse(da);
                LocalDate date2 = date1.plusMonths(3);
TemporalField fieldISO = WeekFields.of(Locale.FRANCE).dayOfWeek();
lblNewExpiredDate.setText(date2.with(fieldISO, 1).toString()); 
 int k = Integer.parseInt(lblCharges.getText())*3;
 lblAmountPay.setText(Integer.toString(k));
    }
       else if (c.equals("Nine Month")){
        
           LocalDate date1 = LocalDate.parse(da);
                LocalDate date2 = date1.plusMonths(9);
TemporalField fieldISO = WeekFields.of(Locale.FRANCE).dayOfWeek();
lblNewExpiredDate.setText(date2.with(fieldISO, 1).toString()); 
int k = Integer.parseInt(lblCharges.getText())*9;
 lblAmountPay.setText(Integer.toString(k));
    }
       else if (c.equals("One Year")){
      
           LocalDate date1 = LocalDate.parse(da);
                LocalDate date2 = date1.plusMonths(12);
TemporalField fieldISO = WeekFields.of(Locale.FRANCE).dayOfWeek();
lblNewExpiredDate.setText(date2.with(fieldISO, 1).toString()); 
int k = Integer.parseInt(lblCharges.getText())*12;
 lblAmountPay.setText(Integer.toString(k));
    }
        }
        
        
        
    }//GEN-LAST:event_btnSelectDurationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        PaymentSelectionPage a = new PaymentSelectionPage();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnProceedPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedPaymentActionPerformed
        // TODO add your handling code here:
        if(lblNewExpiredDate.getText().isEmpty()||lblAmountPay.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Select Duration Month to Continue!","Field Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            
        
        try { 
         ArrayList<String> nArray= new ArrayList<>();  
          String x;
         
             try (FileReader fr = new FileReader("Customer.txt")) {
                 BufferedReader br=new BufferedReader(fr);
                 while(( x= br.readLine()) != null){
                     String[] parts=x.split("#");
                     String part1 = parts[1]; 
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
String part8 = parts[8];
String part9 = parts[9];
String as = lblCN.getText();
String bb = lblSportName.getText();
String cc = lblCharges.getText();
String ff = lblWeekDate.getText();
String gg= lblNewExpiredDate.getText();
String kk = lblAmountPay.getText();
                     if(parts[1].equals(part1)&&parts[2].equals(as)&&parts[3].equals(bb)&&parts[7].equals(ff)){
                         nArray.add("#"+part1+"#"+as+"#"+bb+"#"+cc+"#"+part5+"#"+part6+"#"+gg+"#"+"Payment Successful"+"#"+gg);
                         
                         
                     }
                     else{
                         nArray.add(x);
                     }
                 
                 }   }
        PrintWriter pw= new PrintWriter("Customer.txt");
        for(String print:nArray){
            pw.println(print);
        }
        pw.close();
        JOptionPane.showMessageDialog(this,"Payment Successfully! Receipt Will Issue!  ","Modify", JOptionPane.INFORMATION_MESSAGE);
        String as = lblCN.getText();
String bb = lblSportName.getText();
String cc = lblCharges.getText();
String ff = lblWeekDate.getText();
String gg= lblNewExpiredDate.getText();
String kk = lblAmountPay.getText();
 DefaultComboBoxModel option = (DefaultComboBoxModel)cboDuration.getModel();
       String c = (String)option.getElementAt(cboDuration.getSelectedIndex());
this.setVisible(false);
new Payment().setVisible(true);
        Receipt r = new Receipt();
        r.Payment(as,bb,cc,ff,gg,kk,c);
        r.setVisible(true);
       
        }
        catch(Exception m) {
         m.printStackTrace();
      }
        }
    }//GEN-LAST:event_btnProceedPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProceedPayment;
    private javax.swing.JButton btnSelectDuration;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboDuration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAmountPay;
    private javax.swing.JLabel lblCN;
    private javax.swing.JLabel lblCharges;
    private javax.swing.JLabel lblExpiredDate;
    private javax.swing.JLabel lblNewExpiredDate;
    private javax.swing.JLabel lblSportName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblWeekDate;
    private javax.swing.JTable tblSport;
    // End of variables declaration//GEN-END:variables
}
