/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportclassfeespaymentsystem;
import java.awt.event.KeyEvent;
import java.io.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.util.*;
import java.util.regex.Pattern;
/**
 *
 * @author Hoo Jun Yi
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboGender = new javax.swing.JComboBox<>();
        cboRole = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        txtReenter = new javax.swing.JPasswordField();
        btnChkName = new javax.swing.JButton();
        txtEmailAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 575));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel1.setText("Registration Customer & Coach Page");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(29, 19, 574, 44);

        btnRegister.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(440, 460, 120, 40);

        btnCancel.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(580, 460, 130, 40);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel2.setText("First Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 84, 62, 16);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(73, 134, 59, 16);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel4.setText("Username :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(74, 189, 58, 16);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel5.setText("Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(76, 237, 56, 16);

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });
        getContentPane().add(txtFirstName);
        txtFirstName.setBounds(136, 81, 176, 20);

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });
        getContentPane().add(txtLastName);
        txtLastName.setBounds(136, 131, 176, 20);
        getContentPane().add(txtUsername);
        txtUsername.setBounds(136, 186, 176, 20);
        getContentPane().add(txtAddress);
        txtAddress.setBounds(135, 298, 177, 20);

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel6.setText("Address :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(83, 301, 48, 16);

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel7.setText("Role :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(101, 377, 30, 16);

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel8.setText("Contact Number :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(38, 339, 93, 16);

        txtContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumberActionPerformed(evt);
            }
        });
        txtContactNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNumberKeyTyped(evt);
            }
        });
        getContentPane().add(txtContactNumber);
        txtContactNumber.setBounds(135, 336, 177, 20);

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel9.setText("Gender :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(85, 424, 44, 16);

        cboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGenderActionPerformed(evt);
            }
        });
        getContentPane().add(cboGender);
        cboGender.setBounds(133, 421, 179, 20);

        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Coach" }));
        cboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRoleActionPerformed(evt);
            }
        });
        getContentPane().add(cboRole);
        cboRole.setBounds(135, 374, 177, 20);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(136, 234, 176, 20);

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel11.setText("Re-enter Password :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(28, 263, 104, 16);

        txtReenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReenterActionPerformed(evt);
            }
        });
        getContentPane().add(txtReenter);
        txtReenter.setBounds(136, 260, 176, 20);

        btnChkName.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnChkName.setText("Check Username");
        btnChkName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChkNameActionPerformed(evt);
            }
        });
        getContentPane().add(btnChkName);
        btnChkName.setBounds(330, 187, 160, 20);

        txtEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailAddressKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailAddressKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmailAddress);
        txtEmailAddress.setBounds(133, 459, 179, 20);

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel10.setText("Email Address :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 462, 79, 16);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportclassfeespaymentsystem/Best-Green-Backgrounds.jpeg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, -36, 1010, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGenderActionPerformed

    private void cboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRoleActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
         

        String a = new String(txtPassword.getPassword());
        String b = new String(txtReenter.getPassword());
        if(txtUsername.getText().equals("") || txtFirstName.getText().equals("") || txtLastName.getText().equals("") || a.equals("") || b.equals("") || txtAddress.getText().equals("")  || txtContactNumber.getText().equals("") || txtEmailAddress.getText().equals(""))
            {
               JOptionPane.showMessageDialog(this,"No Field Is Enter Or One Field Is Empty","Field Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
            if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", txtEmailAddress.getText()))) { 
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE); 
        } 
        else 
        { 
            
                        if(txtReenter.getText().equals(txtPassword.getText())){
               DefaultComboBoxModel option = (DefaultComboBoxModel)cboRole.getModel();
       String c = (String)option.getElementAt(cboRole.getSelectedIndex());
        DefaultComboBoxModel option2 = (DefaultComboBoxModel)cboGender.getModel();
       String d = (String)option2.getElementAt(cboGender.getSelectedIndex());
        //List<String> list = new ArrayList<String>();
       

        File file = new File("Login.txt");
        try{               
           
            FileWriter output1 = new FileWriter(file,true);
   
            output1.write("#"+txtFirstName.getText());
            output1.write("#"+txtLastName.getText());
            output1.write("#"+txtUsername.getText());
            output1.write("#"+a);
            output1.write("#"+b);
            output1.write("#"+txtAddress.getText());
            output1.write("#"+txtContactNumber.getText());
            output1.write("#"+c);
            output1.write("#"+d);
            output1.write("#"+txtEmailAddress.getText());
            output1.write(System.lineSeparator());
            output1.close();
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame, "Register Complete!");
            txtFirstName.setText("");
            txtLastName.setText("");
            txtUsername.setText("");
            txtPassword.setText("");
            txtReenter.setText("");
            txtAddress.setText("");
            txtContactNumber.setText("");
            txtEmailAddress.setText("");
            
        } catch (IOException ex){
            JOptionPane.showMessageDialog(this,"Write File Error","Register Error",JOptionPane.ERROR_MESSAGE);
        }               
            }
            else{
              JOptionPane.showMessageDialog(this,"Password is not match","Password Error",JOptionPane.ERROR_MESSAGE);
           }
        }

            
        
        
            }
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtReenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReenterActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        StaffMainPage a = new StaffMainPage();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtContactNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNumberKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
           getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtContactNumberKeyTyped

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

    if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE ))
        evt.consume();
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

    if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE ))
        evt.consume();
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void btnChkNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChkNameActionPerformed
        // TODO add your handling code here:
        if (txtUsername.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please don't leave username field blank!","Username Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try
{


FileReader input=new FileReader("Login.txt");
BufferedReader output = new BufferedReader(input);
String code;
while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String part3 = parts[3];
String UN = txtUsername.getText();
if (UN.equals(part3))
{
JOptionPane.showMessageDialog(this,"Username is already exist in the system! Please enter another username!","Register Error",JOptionPane.ERROR_MESSAGE);
btnRegister.setEnabled(false);
break;
}
else{
    btnRegister.setEnabled(true);
}
} else {
    throw new IllegalArgumentException("String " + code + " does not contain -");
}
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
        }
        
        
    }//GEN-LAST:event_btnChkNameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
                btnRegister.setEnabled(false);
                JOptionPane.showMessageDialog(this,"Please click the check username button after entering username to proceed!","Check Username",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_formWindowOpened

    private void txtEmailAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddressKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmailAddressKeyReleased

    private void txtEmailAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddressKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtEmailAddressKeyPressed

    private void txtContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChkName;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cboGender;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtReenter;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
