/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportclassfeespaymentsystem;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.temporal.TemporalField;
import java.time.temporal.WeekFields;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hoo Jun Yi
 */
public class ViewAllSport extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllSport
     */
    public ViewAllSport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSport = new javax.swing.JTable();
        btnFilter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSportName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCharges = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDayOfTheWeek = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblWeekDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSelectSport = new javax.swing.JButton();
        cboCoach = new javax.swing.JComboBox<>();
        cboCN = new javax.swing.JComboBox<>();
        lblCoachName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 610));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel1.setText("View and Choose Sports");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 11, 374, 44);

        btnBack.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1050, 490, 110, 50);

        tblSport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Coach Name", "Sport Name", "Sport Charges Per Month", "Day Of The Week", "Time", "Sport Description", "Week Date"
            }
        ));
        tblSport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSportMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSport);
        if (tblSport.getColumnModel().getColumnCount() > 0) {
            tblSport.getColumnModel().getColumn(0).setMinWidth(0);
            tblSport.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSport.getColumnModel().getColumn(6).setMinWidth(300);
            tblSport.getColumnModel().getColumn(6).setMaxWidth(300);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(23, 92, 1154, 303);

        btnFilter.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnFilter.setText("Coach Filter By");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        getContentPane().add(btnFilter);
        btnFilter.setBounds(735, 27, 150, 25);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel3.setText("Coach Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(475, 31, 71, 16);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel4.setText("Customer Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 430, 90, 16);

        lblSportName.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblSportName);
        lblSportName.setBounds(160, 460, 103, 16);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel5.setText("Sport Name :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 460, 69, 16);

        lblCharges.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblCharges);
        lblCharges.setBounds(170, 490, 103, 16);

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel6.setText("Sport Charges Per Month:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 490, 135, 16);

        lblDayOfTheWeek.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblDayOfTheWeek);
        lblDayOfTheWeek.setBounds(160, 510, 103, 16);

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel7.setText("Day Of The Week :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 510, 94, 16);

        lblTime.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblTime);
        lblTime.setBounds(160, 530, 103, 16);

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel8.setText("Time :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 530, 32, 16);

        lblWeekDate.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblWeekDate);
        lblWeekDate.setBounds(160, 550, 103, 16);

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel9.setText("Week Date :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 550, 62, 16);

        btnSelectSport.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnSelectSport.setText("Select Sport And Proceed Payment");
        btnSelectSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSportActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectSport);
        btnSelectSport.setBounds(510, 420, 290, 78);

        getContentPane().add(cboCoach);
        cboCoach.setBounds(549, 28, 168, 20);

        cboCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCNActionPerformed(evt);
            }
        });
        getContentPane().add(cboCN);
        cboCN.setBounds(160, 430, 168, 20);

        lblCoachName.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        getContentPane().add(lblCoachName);
        lblCoachName.setBounds(160, 410, 103, 16);

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel10.setText("Coach Name :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 410, 71, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportclassfeespaymentsystem/Best-Green-Backgrounds.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 10, 1320, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         PaymentSelectionPage a = new PaymentSelectionPage();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblSportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSportMouseClicked
        // TODO add your handling code here:
        int index = tblSport.getSelectedRow();
        TableModel model = tblSport.getModel();
lblCoachName.setText(model.getValueAt(index,1).toString());
        lblSportName.setText(model.getValueAt(index,2).toString());
        lblCharges.setText(model.getValueAt(index,3).toString());
        lblDayOfTheWeek.setText(model.getValueAt(index,4).toString());
        lblTime.setText(model.getValueAt(index,5).toString());

       
    }//GEN-LAST:event_tblSportMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LocalDate date = LocalDate.now();
        TemporalField fieldISO = WeekFields.of(Locale.FRANCE).dayOfWeek();
lblWeekDate.setText(date.with(fieldISO, 1).toString()); 
        try
{


FileReader input=new FileReader("Login.txt");
BufferedReader output = new BufferedReader(input);
String code;
DefaultComboBoxModel nameopt2 = new DefaultComboBoxModel();
        cboCN.setModel(nameopt2);
while((code=output.readLine())!=null)
{
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String part1 = parts[1];
String part8 = parts[8];
if (part8.equals("Customer")){
    nameopt2.addElement(part1);
}


        
} 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
        try
{


FileReader input=new FileReader("Login.txt");
BufferedReader output = new BufferedReader(input);
String code;
DefaultComboBoxModel nameopt = new DefaultComboBoxModel();
        cboCoach.setModel(nameopt);
while((code=output.readLine())!=null)
{
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String part1 = parts[1];
String part8 = parts[8];
if (part8.equals("Coach")){
    nameopt.addElement(part1);
}


        
} 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
        
        
                DefaultTableModel tableModel = (DefaultTableModel)tblSport.getModel();
    String line;
    
BufferedReader reader;
    try{       

        reader = new BufferedReader(new FileReader("Coach.txt"));
        while((line = reader.readLine()) != null) 
        {
//            if (line.contains("Customer")) {
    // Split it.
   
    tableModel.addRow(line.split("#")); 

           
//        }
        }
        reader.close();
     }
    
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
    }//GEN-LAST:event_formWindowOpened

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel)tblSport.getModel();
        tableModel.setRowCount(0);
    String line;
    
BufferedReader reader;
    try{       
        DefaultComboBoxModel option2 = (DefaultComboBoxModel)cboCoach.getModel();
         String c = (String)option2.getElementAt(cboCoach.getSelectedIndex());
        

        reader = new BufferedReader(new FileReader("Coach.txt"));
        while((line = reader.readLine()) != null) 
        {
            if (line.contains(c)) {
    // Split it.
   
    tableModel.addRow(line.split("#")); 

           
        }
        }
        reader.close();
     }
    
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnSelectSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSportActionPerformed
        // TODO add your handling code here:

            
        //List<String> list = new ArrayList<String>();
        
       
         DefaultComboBoxModel option3 = (DefaultComboBoxModel)cboCN.getModel();
         String d = (String)option3.getElementAt(cboCN.getSelectedIndex());
            String e = lblCoachName.getText();
            String f = lblSportName.getText();
            String g = lblCharges.getText();
            String h = lblDayOfTheWeek.getText();
            String i = lblTime.getText();
            String j = lblWeekDate.getText();
            int flag = 0;
            if(e.isEmpty() || f.isEmpty() || g.isEmpty()||h.isEmpty()||i.isEmpty()||j.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"No Field Is Enter Or One Field Is Empty","Field Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                 try
{


FileReader input=new FileReader("Customer.txt");
BufferedReader output = new BufferedReader(input);
String code;

while((code=output.readLine())!=null)
{
System.out.println(code);
    
if (code.contains("#")) {
    // Split it.
    String[] parts = code.split("#");


String part1 = parts[1]; 
String part2 = parts[2];
String part3 = parts[3];
String part4 = parts[4];
String part5 = parts[5];
String part6 = parts[6];
String part7 = parts[7];
String part8 = parts[8];
String part9 = parts[9];



if (d.equals(part2)&&lblSportName.getText().equals(part3))
{
JOptionPane.showMessageDialog(this,"Cutomer Already has the sport course","Select Sport Error",JOptionPane.ERROR_MESSAGE);
flag =0;
break;
}
else{
  flag =1;
}
} 
}
input.close();
}
catch(IOException ioe)
{
	ioe.printStackTrace();	
	System.out.println("Error");
}
                 if(flag==1){
                      File file = new File("Customer.txt");
        try{               
            //int x = xArrayList.size();
           // for (int i = 0; i < datList; i++) {
           //     pw.write(datArrayList.get(i).toString() + "\n");
            //}
           
            FileWriter output1 = new FileWriter(file,true);
            //array[0] = output.write(txtFirstName.getText());
            output1.write("#"+e);
            output1.write("#"+d);
            output1.write("#"+f);
            output1.write("#"+g);
            output1.write("#"+h);
            output1.write("#"+i);
            output1.write("#"+j);
            output1.write("#"+"Payment Pending");
            output1.write("#"+"Duration Pending");
            
            output1.write(System.lineSeparator());
            output1.close();
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame, "Register Sport Complete! Please go to the counter to make payment!");
             Payment r = new Payment();
        r.ViewAllSport(d,f,g,j);
        r.setVisible(true);
        dispose();
            lblSportName.setText("");
            lblCharges.setText("");
            lblDayOfTheWeek.setText("");
            lblTime.setText("");
            lblWeekDate.setText("");
                  } catch (IOException ex){
            JOptionPane.showMessageDialog(this,"Write File Error","Register Error",JOptionPane.ERROR_MESSAGE);
        } 
                 }     
       
            
        
            }
           
            
            
    }//GEN-LAST:event_btnSelectSportActionPerformed

    private void cboCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllSport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnSelectSport;
    private javax.swing.JComboBox<String> cboCN;
    private javax.swing.JComboBox<String> cboCoach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCharges;
    private javax.swing.JLabel lblCoachName;
    private javax.swing.JLabel lblDayOfTheWeek;
    private javax.swing.JLabel lblSportName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWeekDate;
    private javax.swing.JTable tblSport;
    // End of variables declaration//GEN-END:variables
}
